#version 460 core

#define LOCAL_COUNT 12

layout (local_size_x = LOCAL_COUNT, local_size_y = LOCAL_COUNT) in;

layout(binding = 0) uniform sampler2D inputTexture;
layout(binding = 1, rgba8) uniform image2D imgOutput;

void main()
{
	ivec2 texelCoord = ivec2(gl_GlobalInvocationID.xy);
	vec2 size = vec2(imageSize(imgOutput));
	
	vec4 value = texture(inputTexture, vec2(texelCoord)/size);
	value.x += 0.5;
	value.z += 0.5;
	
    imageStore(imgOutput, texelCoord, value);
}