
// SSBOs
#define GRASS_LOCATION 0

// UBOs
#define GRASS_MATERIAL_LOCATION 1

// Texture Units
#define DISPLACEMENT_MAP_TEXTURE_UNIT 4
#define NOISE_TEXTURE_UNIT 5
#define WIND_NOISE_TEXTURE_UNIT 6
#define HEIGHT_MAP_TEXTURE_UNIT 7
#define COLOR_MAP_TEXTURE_UNIT 10
#define LENGTH_MAP_TEXTURE_UNIT 11
